### PR TITLE
fixes: don't attempt download when html or css downloads external resources

### PR DESCRIPTION
**Pull request by joriverm**
came across this bug when integrating the control. our app.css was referencing external fonts sooo :)

### CODE REVIEW

**Comment by jpmikkers** [comment]
Oof, that's almost certainly an issue in FilteringRequestHandler.cs because when I look at the original https://github.com/dotnet/maui/blob/96288c1cff1c6399f42e3e24ea6f5b54557a19c0/src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs , they must be intercepting those requests earlier.

**Comment by joriverm** [comment]
ah, i see. i will look into it!

**Comment by joriverm** [comment]
so i did some investigations and i think Microsoft's webview is indeed intercepting it and not handling it as a 'navigation' but rather as a `HandleWebResourceRequest`. thats just my guess though.

i think we should somehow get the `FilteringRequestHandler` (which is part of the adaptor) to only trigger the navigation if it is navigating away and not a request part of the page's content

**Comment by jpmikkers** [comment]
Do you perhaps have a small html / css example that demonstrates the difference in behavior? Or do you do it by watching outgoing connections or something like that?

**Comment by joriverm** [comment]
ah ye, sorry. i was getting it using internal hosted css.
add the following into the app.css : 
```
@font-face {
    font-family: "ugent-panno";
    src: url(https://fonts.gstatic.com/s/crimsonpro/v24/q5uDsoa5M_tv7IihmnkabARUoYFoCQ.woff2) format('woff2');
    font-display: swap;
}


body {
    --navmenu-margin: 10px;
    --header-height: 50px;
    --body-font: ugent-panno;
    font-family: var(--body-font);
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    margin: 0;
}
```

**Comment by joriverm** [comment]
i rebased my branch and fixed the issue by only triggering the navigation even if CEF reports the request as a navigation. this fixes the issue

meanwhile, i also refactored the webview for WPF a bit to be more like the control they made.

**Comment by jpmikkers** [comment]
meanwhile I cherry picked that last commit (slightly tweaked to keep one of my fixes)

**Comment by joriverm** [comment]
huh? i have no idea what happened to main. it says you cherry picked but then reverted? its conflicting with what i have in this branch, but no idea why or what. 

what was it that you fixed?

**Comment by jpmikkers** [comment]
I cherry picked, reverted and cherry picked again. (Didn't mean to but accidentally pushed while fixing the design view crash)

this 'if' is still needed to prevent design view crash: 
https://github.com/jpmikkers/Baksteen.Blazor.CefSharp/blob/main/Baksteen.Blazor.CefSharpWPF%2FBlazorCefWebView.cs#L86

**Comment by jpmikkers** [comment]
By the way I've been looking at which event handlers trigger for the original CoreWebView2 when loading the font.. well it turns out, none of them do (except for CoreWebView2.WebResourceResponseReceived, but that is only after the fact). 

See also this [stackoverflow question](https://stackoverflow.com/questions/77700424/webview2-intercept-inner-css-file-redirection) , people can't intercept the font download **even if they want to**.

**Comment by joriverm** [comment]
i rebased my branch (again) to no longer include the commit you cherry picked. not sure why you didn't just ask me to change the commit to include your fix. would've made it easier for us both :)

anyway, if their navigation event isn't triggered, then i can only assume my fix is correct and that stuff like that doesn't trigger any events. i fixed that by checking the `isNavigation` of `GetResourceRequestHandler`

**Pull request merged**
